stages:
  - prepare
  - lint
  - build
  - publish

include:
  # Prepare
  - project: 'intern/runner-templates'
    ref: "1.1"
    file: '/yarn/install-js-dependencies.yml'

  # Lint
  - project: 'intern/runner-templates'
    ref: "1.1"
    file: '/ts/tslint.yml'

  # Build
  - project: 'intern/runner-templates'
    ref: "1.1"
    file: '/yarn/build-prod.yml'

install-js-dependencies:
  except:
    - schedules
    - master

ts-analysis:
  except:
    - schedules
    - tags
    - master

build-assets:
  needs:
    - install-js-dependencies
  artifacts:
    when: on_failure
    untracked: true
  except:
    - schedules
    - tags
    - master

publish-pkg:
  stage: publish
  image: node:16.15.0-alpine
  resource_group: $CI_JOB_NAME
  needs:
    - install-js-dependencies
  script:
    - echo "username=${NPM_USER}" > .npmrc
    - echo "_password=$(echo -n ${NPM_PASS} | base64)" >> .npmrc
    - echo "email=${NPM_EMAIL}" >> .npmrc
    - echo "always-auth=true" >> .npmrc
    - yarn version --new-version ${CI_COMMIT_TAG} --no-git-tag-version
    - yarn publish
  after_script:
    - rm .npmrc
  tags:
    - docker
  only:
    - tags

publish-pkg-npmjs:
  stage: publish
  image: node:16.15.0-alpine
  resource_group: ${CI_JOB_NAME}_npmjs
  needs:
    - install-js-dependencies
  script:
    - echo "username=${NPMJS_USER}" >> .npmrc
    - echo "email=${NPMJS_EMAIL}" >> .npmrc
    - echo "always-auth=true" >> .npmrc
    - echo "//${NPMJS_REGISTRY}/:_authToken=${NPMJS_TOKEN}" >> .npmrc
    - echo "registry \"https://${NPMJS_REGISTRY}\"" >> .yarnrc
    - yarn version --new-version ${CI_COMMIT_TAG} --no-git-tag-version
    - yarn publish --access public
  after_script:
    - rm .npmrc
    - git checkout .yarnrc
  tags:
    - docker
  only:
    - tags
